#!/usr/bin/env python3
"""Produce the example findings register in ``examples/`` using the real API.

This drives the FULL polistress pipeline — ingest → synthesize → simulate →
report — over the synthetic organization, making **real Anthropic API calls**
for every agent decision and for findings synthesis. No decisions are faked.

Credentials are read from the environment (``ANTHROPIC_API_KEY`` or
``ANTHROPIC_AUTH_TOKEN``). Because a full 150-person / 30-tick run is thousands
of calls, this example defaults to a small, representative agent subset and a
short horizon so it completes quickly and within modest rate limits. Scale it
up with ``--agents`` / ``--ticks`` (or run ``polistress simulate`` directly).

Run: ``python examples/generate_example.py``
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

from polistress.llm_client import has_credentials
from polistress.personas import synthesize_agents
from polistress.personas.agent import Agent, Archetype
from polistress.personas.memory import AgentMemory
from polistress.report import ReportAgent
from polistress.report.backend import AnthropicReportBackend
from polistress.report.findings import write_csv, write_json
from polistress.simulation import EventLog, SimulationEngine, load_scenario
from polistress.simulation.decider import AnthropicDecider
from polistress.worldgraph import ingest_directory

ROOT = Path(__file__).resolve().parents[1]
SEED_DIR = ROOT / "data" / "synthetic_org"
SCENARIO = ROOT / "scenarios" / "ai_usage_policy.yaml"
OUT = ROOT / "examples"

# A small, archetype-diverse subset so shadow-AI / attacker signals still emerge
# while keeping the real-call count low. (developer, ai_agent, ciso, auditor,
# employee, attacker are all represented.)
_SUBSET = {
    Archetype.CISO: 1,
    Archetype.AUDITOR: 1,
    Archetype.DEVELOPER: 3,
    Archetype.AI_AGENT: 2,
    Archetype.EMPLOYEE: 2,
    Archetype.SYSADMIN: 1,
}


def _representative_subset(agents: list[Agent]) -> list[Agent]:
    chosen: list[Agent] = []
    for archetype, n in _SUBSET.items():
        chosen.extend([a for a in agents if a.archetype == archetype][:n])
    chosen.extend(a for a in agents if a.archetype == Archetype.ATTACKER)
    return chosen


async def run(agents_cap: int | None, ticks: int, concurrency: int) -> None:
    graph = ingest_directory(SEED_DIR)
    scenario = load_scenario(SCENARIO)
    all_agents = synthesize_agents(graph, seed=0, n_attackers=1)
    agents = _representative_subset(all_agents)
    if agents_cap is not None:
        agents = agents[:agents_cap]

    run_dir = OUT / "_run"
    run_dir.mkdir(parents=True, exist_ok=True)
    for name in ("events.db", "memory.db"):
        p = run_dir / name
        if p.exists():
            p.unlink()

    log = EventLog(run_dir / "events.db")
    memory = AgentMemory(run_dir / "memory.db")
    decider = AnthropicDecider(max_concurrency=concurrency, max_retries=8)
    engine = SimulationEngine(graph, agents, log, memory, decider)

    print(
        f"Running {len(agents)} agents x {ticks} ticks with REAL API calls "
        f"(concurrency={concurrency})…",
        flush=True,
    )
    await engine.run(scenario, ticks)

    backend = AnthropicReportBackend(max_retries=8)
    report = ReportAgent(graph, log, backend, domain=scenario.domain)
    findings = await report.build_findings()

    write_json(findings, OUT / "findings.json")
    write_csv(findings, OUT / "findings.csv")

    question = "where did shadow AI emerge?"
    answer = await report.answer(question)

    counts = log.action_counts()
    _write_summary(
        OUT / "run_summary.md", scenario, agents, ticks, counts, findings, question, answer
    )
    log.close()
    memory.close()
    print(
        f"Wrote {len(findings)} findings from {sum(counts.values())} real events "
        f"({len(agents)} agents x {ticks} ticks) to examples/."
    )


def _write_summary(path, scenario, agents, ticks, counts, findings, question, answer) -> None:
    lines = [
        f"# Example run summary — {scenario.name}",
        "",
        "> Generated by `examples/generate_example.py` over the synthetic org,",
        "> with **real Anthropic API calls** for every agent decision and for",
        "> findings synthesis. Small scope (few agents, short horizon) so it",
        "> completes quickly; scale up with `--agents` / `--ticks` or run",
        "> `polistress simulate` for the full 150-person / 30-tick scenario.",
        "",
        f"- Agents: **{len(agents)}** "
        + "(" + ", ".join(sorted({a.archetype.value for a in agents})) + ")",
        f"- Ticks: **{ticks}**",
        f"- Total events: **{sum(counts.values())}**",
        "",
        "## Action distribution",
        "",
        "| action | count |",
        "|---|---:|",
    ]
    for action, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {action} | {n} |")
    lines += ["", "## Findings", "", "| id | severity | title | citations |", "|---|---|---|---:|"]
    for f in findings:
        lines.append(f"| {f.id} | {f.severity} | {f.title} | {len(f.root_cause_events)} |")
    lines += [
        "",
        "## Sample Q&A",
        "",
        f"**Q:** {question}",
        "",
        f"**A:** {answer.text}",
        "",
        "_Cited events: "
        + (", ".join(f"evt-{i}" for i in answer.cited_event_ids) or "(none)")
        + "_",
        "",
    ]
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--agents", type=int, default=None, help="cap on agents (subset)")
    parser.add_argument("--ticks", type=int, default=2, help="simulated ticks")
    parser.add_argument("--concurrency", type=int, default=1, help="max concurrent calls")
    args = parser.parse_args()

    if not has_credentials():
        sys.exit(
            "No Anthropic credentials. Set ANTHROPIC_API_KEY or ANTHROPIC_AUTH_TOKEN "
            "— this example makes real API calls."
        )
    asyncio.run(run(args.agents, args.ticks, args.concurrency))


if __name__ == "__main__":
    main()
