"""polistress — swarm-based GRC policy simulation engine.

All seed organizational data shipped with or generated by this package is
synthetic. It does not describe any real organization or person.
"""

__version__ = "0.1.0"
